resolver kube-dns.kube-system.svc.cluster.local valid=30s ipv6=off;

server {
    listen 80;

    location /google {
        proxy_ssl_server_name on;
        proxy_pass https://www.google.com;
    }
}
